apiVersion: apps/v1
kind: Deployment
metadata:
  name: maradio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maradio
  template:
    metadata:
      labels:
        app: maradio
    spec:
      containers:
      - name: maradio
        image: eazytrainingacr.azurecr.io/maradioprod:$(Build.BuildId)
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: maradio
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: maradio
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maradio
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: maradio.211b8e8d5df2453fafc7.francecentral.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maradio
            port:
              number: 80

