apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: maradio
spec:
  maxReplicas: 20
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maradio
